//USE ROLE DS5111_DBT;
//USE DATABASE DS5111_SU24;
//-- CREATE SCHEMA etc7fq;
//USE SCHEMA etc7fq

//QUERY1
SELECT MNEMONIC, NAME
FROM COURSES
WHERE ACTIVE = TRUE;

//QUERY2
SELECT MNEMONIC, NAME
FROM COURSES
WHERE ACTIVE = FALSE;

//QUERY3
SELECT INSTRUCTOR
FROM INSTRUCTORS
WHERE ACTIVE = FALSE;

//QUERY4
SELECT 
    C.MNEMONIC,
    C.NAME,
    COUNT(LO.LEARNING_OUTCOME) AS LEARNING_OUTCOME_COUNT
FROM 
    COURSES C
LEFT JOIN 
    LEARNING_OUTCOMES LO 
    ON C.MNEMONIC = LO.MNEMONIC
GROUP BY 
    C.MNEMONIC, C.NAME
ORDER BY
    C.MNEMONIC;

//QUERY5
SELECT 
    C.MNEMONIC,
    C.NAME,
    COUNT(LO.LEARNING_OUTCOME) AS LEARNING_OUTCOME_COUNT
FROM 
    COURSES C
LEFT JOIN 
    LEARNING_OUTCOMES LO 
    ON C.MNEMONIC = LO.MNEMONIC
GROUP BY 
    C.MNEMONIC, C.NAME
HAVING
    COUNT(LO.LEARNING_OUTCOME)=0
ORDER BY
    C.MNEMONIC;

//QUERY6
SELECT 
    C.MNEMONIC,
    C.NAME,
    LO.LEARNING_OUTCOME
FROM 
    COURSES C
INNER JOIN 
    LEARNING_OUTCOMES LO ON C.MNEMONIC = LO.MNEMONIC
WHERE 
    LO.LEARNING_OUTCOME LIKE '%SQL%'
ORDER BY 
    C.MNEMONIC;

//QUERY7
SELECT 
    S.INSTRUCTOR
FROM 
    SEMESTERS S
WHERE 
    S.MNEMONIC = 'ds5100' 
    AND S.SEMESTER = 'SUMMER2021';

//QUERY8
SELECT 
    DISTINCT S.INSTRUCTOR
FROM 
    SEMESTERS S
WHERE 
    S.SEMESTER = 'FALL2021'
ORDER BY 
    S.INSTRUCTOR ASC;

//QUERY9
SELECT 
    S.SEMESTER,
    S.INSTRUCTOR,
    COUNT(S.MNEMONIC) AS COURSE_COUNT
FROM 
    SEMESTERS S
GROUP BY 
    S.SEMESTER, S.INSTRUCTOR
ORDER BY 
    S.SEMESTER ASC, S.INSTRUCTOR ASC;

//QUERY10A
SELECT 
    S.MNEMONIC,
    S.SEMESTER
FROM 
    SEMESTERS S
WHERE 
    S.INSTRUCTOR LIKE '%,%' OR S.INSTRUCTOR LIKE '%&%'
ORDER BY 
    S.SEMESTER ASC, S.MNEMONIC ASC;

//QUERY10B
WITH coursesWithmultipleSections AS (
    SELECT 
        S.MNEMONIC,
        S.SEMESTER
    FROM 
        SEMESTERS S
    WHERE 
        S.INSTRUCTOR LIKE '%,%' OR S.INSTRUCTOR LIKE '%&%'
)
SELECT 
    S.SEMESTER,
    S.MNEMONIC,
    S.INSTRUCTOR
FROM 
    SEMESTERS S
INNER JOIN 
    coursesWithmultipleSections CMS ON S.MNEMONIC = CMS.MNEMONIC AND S.SEMESTER = CMS.SEMESTER
ORDER BY 
    S.SEMESTER ASC, S.MNEMONIC ASC, S.INSTRUCTOR ASC;






